// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/22/2026, 8:49:58 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/plugins/**/*.{js,ts,mjs}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/composables/**/*.{js,ts,mjs}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/utils/**/*.{js,ts,mjs}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/amitsinha/Devzign/iOS Native/hyperhabits/hyper-habits-app/rojgar_app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;