CREATE TABLE IF NOT EXISTS cv_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  locale VARCHAR(10) NOT NULL,
  cv_key VARCHAR(100) NOT NULL DEFAULT 'default',
  payload LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_cv_documents_locale_key (locale, cv_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
